### ISSUE TITLE
Create reference database

### ISSUE THREAD

**Issue by dkoslicki** [KoslickiLab/KEGG_sketching_annotation#6]
The goal is to create a reference database of all the genes that were extracted (#5) from the downloaded genomes (#4). This database will be stored in [FASTA format](https://en.wikipedia.org/wiki/FASTA_format). The description line of each entry will look like:
```
>Gene name|gene/protein accession ID| genomic_nucleotide_accession.version | genomic_nucleotide_gi | start position on the genomic accession | end position on the genomic accession
<gene sequence goes here>
```
Those pieces of the header information can be found from the `gene2refseq` file from #5.

The script that does this should take as input the directory that has all the genomes extracted from #4 and the `gene2refseq` file (or the subset of it from #5) and should output the FASTA file in a user-specified location.

**Comment by mahmudhera** [comment]
Some clarification needed in this:

1. Is the gene sequence to be written in the fasta file an amino acid sequence, or a nucleotide sequence?
2. If it is nucleotide sequence, is it always 5’-3’ (meaning: should we use the reverse complement if the strand for the gene is marked as -1?)

**Comment by dkoslicki** [comment]
It should be an amino acid sequence, and written in 5'-3'
